### ISSUE TITLE
Processing cmumosei dataset

### ISSUE THREAD

**Issue by BDHU** [zinengtang/TVLT#3]
I'm interesting in the inference performance using cmumosei dataset. The [README](https://github.com/zinengtang/TVLT/blob/main/DS.md) shows the cmumosei dataset structure, but the actual SDK only downloads `csd` files. How did you extract and process the cmumosei dataset into the said layout? What script are you using to process the cmumosei dataset? Thanks!

**Comment by zinengtang** [comment]
Thanks! We will release the scripts and data for CMU-MOSEI today/tomorrow

**Comment by BDHU** [comment]
Thank you so much for sharing the data! Out of curiosity, why does the dataset only contain `.wav` audio files and no video or text files? Thanks.

**Comment by zinengtang** [comment]
Yeah, there is video and text folders in this dataset. But somehow I didn't create a audio to contain the .wav files. Let me reorganize the folders.

**Comment by BDHU** [comment]
Appreciate the help. Any updates on this matter?

**Comment by zinengtang** [comment]
Now updated thanks!

**Comment by BDHU** [comment]
Thank you very much! I noticed there are some files that are missing. For example, it will say `[17:11:20] /github/workspace/src/video/video_reader.cc:83: ERROR opening: ./dataset/cmumosei/test/video/3At-BKm9eYk_3.mp4, No such file or directory` for some video/audio files. Are they left out intentionally? Just wanna make sure I didn't miss anything important:)

**Comment by zinengtang** [comment]
Yeah, some files are missing. The sources of the CMU-MOSEI dataset I downloaded miss some files. This is expected.

**Comment by Changezi001** [comment]
Hi, 

Thank you for sharing the [link](https://github.com/zinengtang/TVLT/blob/main/DS.md) to the CMU-MOSEI dataset. I downloaded the dataset, and in the labels\BA folder, what do -1, -2, -3, 0, 1, 2, 3 correspond to? Because the CMU-MOSEI dataset has labels for six basic emotions, why do we have seven here, and could you tell me which label corresponds to which emotion?
