### ISSUE TITLE
CUDA memory error

### ISSUE THREAD

**Issue by Park-ing-lot** [zinengtang/TVLT#7]
Hey! When I try to fine-tune TVLT on audio-video retrieval tasks such as MSR-VTT,
I encountered the cuda memory error with A6000 (49G) even though 4 batch sizes per GPU.
(I didn't change anything from your code.)

The paper says all experiments are conducted with A6000, so can you tell me the exact settings?

**Comment by zinengtang** [comment]
Did you use mixed precision training? If it still does not work, you can try decreasing batch size which should not affect the performance too much.

**Comment by Park-ing-lot** [comment]
When I try to change 'draw_false_video' config to 1, it works. I'll try the mixed precision training and batch size decreasing. Thanks!
